/** Public paths for guided demo — generated by scripts/generate-demo-enhancement-images.mjs */
export const DEMO_LAND_RECORD_BEFORE = "/demo/land-record-before.jpg";
export const DEMO_LAND_RECORD_AFTER = "/demo/land-record-after.jpg";
export const DEMO_UPLOAD_FILENAME = "UP_LandRecord_1998.pdf";
